### ISSUE TITLE
Connecting AirSim/Running Scripts

### ISSUE THREAD

**Issue by MrClemmy** [jcarcamo/sar-deep-rl#3]
This may be a trivial issue, but I have been trying to work with this for about a month with nothing to show for it. 

I can't find any documentation explaining _how_ to connect AirSim with UE4, and trying to run any scripts just results in errors. 

I have a conda environment with all the requirements, but I can't set it as an interpreter in UE. We have the AirSim plugin working, but don't know where to go from there. 

Any help would be appreciated,
thank you!

Edit 1: I have figured out how to put scripts in the Win64 directory in Unreal Engine and then call them through the Anaconda terminal, however there are many files which it cannot locate at all such as "MultirotorClient", which I can't find in the official AirSim documentation.

**Comment by jcarcamo** [comment]
Hi @MrClemmy,

In the link [Creating and Setting Up Unreal Environment](https://github.com/Microsoft/AirSim/blob/297f1c49d3ef0a1a0f0d841ef7dafa89603db327/docs/unreal_custenv.md#creating-and-setting-up-unreal-environment) you can find detailed instructions on how to run AirSim in unreal. They have a video in that document in case you prefer a more visual explanation ([Unreal AirSim Setup from scratch](https://youtu.be/1oY8Qu5maQQ?si=lI-o29xe4wDQalwx)) 

Once you have AirSim running, you must provide the path to your AirSim folder, where you'll find a folder called `PythonClient`. This needs to be updated in the file `airsimapi.py` within this project. At the time of writing this project there wasn't a Pyp package for this library, so that's how I solved that issue. I know it could be implemented better, but I did the best I could at the time.

From there on there's a lot of improvements that can take place in this code base, so feel free to create as many PRs as you feel like it. Hope this information is enough for you to get started.

Have a nice day!

**Comment by MrClemmy** [comment]
Unfortunately, this still does not work. 

I have changed the sys.path.append line in airsimapi.py to my own  AirSim>PythonClient folder, but upon running the program it says the module PythonClient can't be found. It starts working if I copy the PythonClient folder into the sar-deep-rl folder, but then it throws an error that 'MultirotorClient' is not defined. I have also tried manually adding the path via my Environment Variables and using conda-build to add the path there but still no luck. 

Are there any dependencies missing from the requirements.txt? 

Edit 1: Would you also recommend keeping the project folders on C: drive or did you not experience any issues with file location? I know the AirSim documentation mentioned having it on C: drive could cause issues. 

Is there another directory in AirSim or ue4 that I should move the project files to?
